const moment=require('moment')
Page({
  data:{
    disabled:false,
    date:moment().format('YYYY-MM-DD'),
    userList:[],
    title:"",
    des:"",
    projectMessage:{},
    avatar:[]
  },
  chooseMember(){
    this.setData({
      disabled:true
    })
  },
  bindDateChange(e){
    this.setData({
      date:e.detail.value
    })
  },
  handleBlur(e){
    if(e.currentTarget.dataset.type==='input'){
      this.setData({
        title:e.detail.value
      })
    }else{
      this.setData({
        des:e.detail.value
      })
    }
  },
  submit(){
    this.setData({
      projectMessage:{
        title:this.data.title,
        des:this.data.des,
        member:this.data.userList,
        start_time:moment().format('YYYY-MM-DD'), 
        end_time:this.data.date
      }
    },()=>{
      wx.request({
        url: 'http://10.9.49.228:9999/api/addPj',
        method:'post',
        data:{
          ...this.data.projectMessage
        },
        success(res){
          console.log(res)
          if(res.data.code===2000){
            wx.navigateBack()
          }
        }
      })
    })
  },
  onMyevent(e){
    let userID=[]
    if(e.detail.chooseUserList){
      e.detail.chooseUserList.forEach(value=>{
        userID.push(value.id)
      })
    }
    this.setData({
      disabled:false,
      avatar:e.detail.chooseUserList,
      userList:userID.toString()
    })
  }
})